/*** Autogenerated by WIDL 10.9 from nvda_rpc_v1.idl - Do not edit ***/
#include <string.h>

#include "nvda_rpc_v1.h"

#define TYPE_FORMAT_STRING_SIZE 11
#define PROC_FORMAT_STRING_SIZE 133

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * NvdaController interface
 */

static RPC_DISPATCH_TABLE NvdaController_v1_0_DispatchTable;
static const MIDL_SERVER_INFO NvdaController_ServerInfo;

static const RPC_SERVER_INTERFACE NvdaController___RpcServerInterface =
{
    sizeof(RPC_SERVER_INTERFACE),
    {{0xdff50b99,0xf7fd,0x4ca7,{0xa8,0x2c,0xda,0xeb,0x3e,0x02,0x52,0x95}},{1,0}},
    {{0x8a885d04,0x1ceb,0x11c9,{0x9f,0xe8,0x08,0x00,0x2b,0x10,0x48,0x60}},{2,0}},
    &NvdaController_v1_0_DispatchTable,
    0,
    0,
    0,
    &NvdaController_ServerInfo,
    0,
};
RPC_IF_HANDLE NvdaController_v1_0_s_ifspec = (RPC_IF_HANDLE)& NvdaController___RpcServerInterface;

static const MIDL_STUB_DESC NvdaController_StubDesc;

#if !defined(__RPC_WIN32__)
#error  Invalid build platform for this stub.
#endif

static const unsigned short NvdaController_FormatStringOffsetTable[] =
{
    0,  /* testIfRunning */
    30,  /* speakText */
    66,  /* cancelSpeech */
    96,  /* brailleMessage */
};

static const MIDL_STUB_DESC NvdaController_StubDesc =
{
    (void *)& NvdaController___RpcServerInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        0,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

static RPC_DISPATCH_FUNCTION NvdaController_table[] =
{
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    NdrServerCall2,
    0
};
static RPC_DISPATCH_TABLE NvdaController_v1_0_DispatchTable =
{
    4,
    NvdaController_table
};

static const SERVER_ROUTINE NvdaController_ServerRoutineTable[] =
{
    (void *)testIfRunning,
    (void *)speakText,
    (void *)cancelSpeech,
    (void *)brailleMessage,
};

static const MIDL_SERVER_INFO NvdaController_ServerInfo =
{
    &NvdaController_StubDesc,
    NvdaController_ServerRoutineTable,
    __MIDL_ProcFormatString.Format,
    NvdaController_FormatStringOffsetTable,
    0,
    0,
    0,
    0
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure NvdaController::testIfRunning) */
        0x33,	/* FC_AUTO_HANDLE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x0),	/* method 0 */
        NdrFcShort(0x4),	/* stack size = 4 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 24 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x10,	/* FC_ERROR_STATUS_T */
        0x0,
/* 30 (procedure NvdaController::speakText) */
        0x33,	/* FC_AUTO_HANDLE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x1),	/* method 1 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 54 (parameter text) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x4),	/* type offset = 4 */
/* 60 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x10,	/* FC_ERROR_STATUS_T */
        0x0,
/* 66 (procedure NvdaController::cancelSpeech) */
        0x33,	/* FC_AUTO_HANDLE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x2),	/* method 2 */
        NdrFcShort(0x4),	/* stack size = 4 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 90 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x0),	/* stack offset = 0 */
        0x10,	/* FC_ERROR_STATUS_T */
        0x0,
/* 96 (procedure NvdaController::brailleMessage) */
        0x33,	/* FC_AUTO_HANDLE */
        0x48,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 120 (parameter message) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x0),	/* stack offset = 0 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 126 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x10,	/* FC_ERROR_STATUS_T */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (const wchar_t *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  4 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 6 (const wchar_t *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/*  8 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
        0x0
    }
};

