/*** Autogenerated by WIDL 10.9 from nvda_rpc_v1.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __nvda_rpc_v1_h__
#define __nvda_rpc_v1_h__

/* Forward declarations */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * NvdaController interface (v1.0)
 */
#ifndef __NvdaController_INTERFACE_DEFINED__
#define __NvdaController_INTERFACE_DEFINED__

extern RPC_IF_HANDLE NvdaController_v1_0_c_ifspec;
extern RPC_IF_HANDLE NvdaController_v1_0_s_ifspec;
error_status_t __stdcall testIfRunning(
    void);

error_status_t __stdcall speakText(
    const wchar_t *text);

error_status_t __stdcall cancelSpeech(
    void);

error_status_t __stdcall brailleMessage(
    const wchar_t *message);


#endif  /* __NvdaController_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __nvda_rpc_v1_h__ */
